version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Containerfile.debian
    container_name: linuxvm
    ports:
      - "80:80"
    volumes:
      - data:/nginx

volumes:
  data:
